app: # 应用基本配置
  env: dev # 环境名称
  port: 9527 # 服务监听端口号
  app_name: gin-app # 应用名称
  app_url: http://localhost # 应用域名
  static_port: 8228
log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: app/app.log # 日志文件名称
  format: # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 60 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 60 # 旧文件的最大保留天数
  compress: true # 是否压缩

mysql:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: gin_gateway # 数据库名称
  username: root # 用户名
  password: root@root # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql/sql.log # 日志文件名称

jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10

cluster:
  cluster_ip: "127.0.0.1"
  cluster_port:  "4356"
  cluster_ssl_port: "8880"

swagger:
  title: "gateway_go project swagger API"
  desc: "gateway_go API 管理"
  host: "127.0.0.1"
  base_path: "/"

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

storage:
  default: local # 默认驱动
  disks:
    local_storage:
      root_file_dir: ./storage/files/ # 文件本地存储根目录
      root_image_dir: ./storage/images/ # 图片本地存储根目录
      root_video_dir: ./storage/videos/ # 视频本地存储根目录
      app_url: http://localhost:8888/storage # 本地图片 url 前部
    ali_oss:
      access_key_id: LTAI5tPaFWokrKh9xxdgeefQ
      access_key_secret: osyjqCvonSKsmAjJIdKP8zdVazVAIw
      bucket: imgg-go
      endpoint: http://oss-cn-beijing.aliyuncs.com
      is_ssl: true # 是否使用 https 协议
      is_private: false # 是否私有读
    ten_cos:
      secretid:
      secretkey:
      cos_url:
    qi_niu:
      access_key:
      bucket:
      domain:
      secret_key:
      is_ssl: true
      is_private: false

#nginx:
#  driver: mysql # 数据库驱动
#  host: 127.0.0.1 # 域名
#  port: 8306 # 端口号
#  database: go-test # 数据库名称
#  username: root # 用户名
#  password: root # 密码
#  charset: utf8mb4 # 编码格式
#  max_idle_conns: 10 # 空闲连接池中连接的最大数量
#  max_open_conns: 100 # 打开数据库连接的最大数量
#  log_mode: info # 日志级别
#  enable_file_log_writer: true # 是否启用日志文件
#  log_filename: sql.log # 日志文件名称
