definitions:
  dao.ServicesInfo:
    properties:
      created_at:
        type: string
      id:
        type: integer
      load_type:
        type: integer
      service_desc:
        type: string
      service_name:
        type: string
      total_node:
        type: integer
      updated_at:
        type: string
    type: object
  dto.AdminInfoOutput:
    properties:
      avatar:
        type: string
      id:
        type: integer
      introduction:
        type: string
      login_time:
        type: string
      name:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  dto.ChangePasswordInput:
    properties:
      newpassword:
        example: 1234_abcd
        type: string
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    type: object
  dto.LoginInput:
    properties:
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    type: object
  dto.LoginOutput:
    properties:
      token:
        example: ""
        type: string
    type: object
  dto.RegisterInput:
    properties:
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    type: object
  dto.ServicesListOutput:
    properties:
      info:
        example: admin
        type: string
      list:
        items:
          $ref: '#/definitions/dao.ServicesInfo'
        type: array
      total:
        example: 400
        type: integer
    type: object
  response.Response:
    properties:
      code:
        description: 自定义错误码
        type: integer
      data:
        description: 数据
      message:
        description: 信息
        type: string
    type: object
host: 127.0.0.1:9527
info:
  contact:
    email: wu_yiqiang@outlook.com
    name: atlas
  description: gin-web框架
  termsOfService: https://github.com/18211167516/Go-Gin-Api
  title: go-api 框架
  version: "1.0"
paths:
  /admin/admin_info:
    get:
      consumes:
      - application/json
      description: 管理员信息获取
      operationId: /admin/admin_info
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      summary: 管理员信息获取
      tags:
      - 用户管理
  /admin/changePassword:
    post:
      consumes:
      - application/json
      description: 修改密码
      operationId: /admin/changePassword
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      summary: 修改密码
      tags:
      - 用户管理
  /admin/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      operationId: /admin/login
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginOutput'
              type: object
      summary: 用户登录
      tags:
      - 用户管理
  /admin/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /admin/register
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 用户管理
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员注销
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      summary: 管理员注销
      tags:
      - 用户管理
  /service/service_list:
    get:
      consumes:
      - application/json
      description: 服务查询
      operationId: /service/service_list
      parameters:
      - description: 服务名
        in: query
        name: info
        type: string
      - description: 页码
        in: query
        name: page_no
        type: integer
      - description: 页数
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ServicesListOutput'
              type: object
      summary: 服务查询
      tags:
      - 服务管理
swagger: "2.0"
