definitions:
  dto.AdminInfoOutput:
    properties:
      avatar:
        type: string
      created_time:
        type: integer
      email:
        type: string
      id:
        type: string
      nickname:
        type: string
      phone:
        type: string
      role:
        type: string
      updated_time:
        type: integer
      username:
        type: string
    type: object
  dto.ChangePasswordInput:
    properties:
      newpassword:
        example: 1234_abcd
        type: string
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    required:
    - newpassword
    - password
    - username
    type: object
  dto.LoginOutput:
    properties:
      token:
        example: ""
        type: string
    type: object
  dto.RegisterInput:
    properties:
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  response.Response:
    properties:
      code:
        description: 自定义错误码
        type: integer
      data:
        description: 数据
      message:
        description: 信息
        type: string
    type: object
host: 127.0.0.1:9527
info:
  contact:
    email: wu_yiqiang@outlook.com
    name: sutter
  description: gin-web框架
  termsOfService: https://github.com/18211167516/Go-Gin-Api
  title: go-api 框架
  version: "1.0"
paths:
  /contact/add:
    post:
      consumes:
      - application/json
      description: 添加好友
      operationId: /contact/add
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 通讯模块
      tags:
      - 通讯模块
  /contact/queryUserFriends:
    post:
      consumes:
      - application/json
      description: 查询好友
      operationId: /contact/queryUserFriends
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      security:
      - Auth: []
      summary: 通讯模块
      tags:
      - 通讯模块
  /file/upload:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: 文件上传
      operationId: /file/upload
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 文件上传
      tags:
      - 文件管理
  /file/uploadFile:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: 文件上传(无分片上传功能)
      operationId: /file/uploadFile
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      - description: 文件名
        in: formData
        name: filename
        required: true
        type: string
      - description: 文件类型
        in: formData
        name: filetype
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 文件上传
      tags:
      - 文件管理
  /user/avatar:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: 管理员头像更新
      operationId: /user/avatar
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 管理员头像更新
      tags:
      - 用户管理
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      operationId: /user/login
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginOutput'
              type: object
      summary: 用户登录
      tags:
      - 用户管理
  /user/logout:
    get:
      consumes:
      - application/json
      description: 用户注销
      operationId: /user/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 用户注销
      tags:
      - 用户管理
  /user/queryUser:
    post:
      consumes:
      - application/json
      description: 用户信息获取
      operationId: /user/queryUser
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      security:
      - Auth: []
      summary: 用户信息获取
      tags:
      - 用户管理
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /user/register
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 用户管理
  /user/updatePassword:
    post:
      consumes:
      - application/json
      description: 修改密码
      operationId: /user/updatePassword
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 修改密码
      tags:
      - 用户管理
securityDefinitions:
  Auth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
