definitions:
  dto.AdminInfoOutput:
    properties:
      avatar:
        type: string
      created_time:
        type: integer
      email:
        type: string
      id:
        type: string
      nick_name:
        type: string
      roles:
        items:
          type: string
        type: array
      update_time:
        type: integer
      user_name:
        type: string
    type: object
  dto.ChangePasswordInput:
    properties:
      newpassword:
        example: 1234_abcd
        type: string
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    required:
    - newpassword
    - password
    - username
    type: object
  dto.LoginOutput:
    properties:
      token:
        example: ""
        type: string
    type: object
  dto.RegisterInput:
    properties:
      password:
        example: 1234_abcd
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  response.Response:
    properties:
      code:
        description: 自定义错误码
        type: integer
      data:
        description: 数据
      message:
        description: 信息
        type: string
    type: object
host: 127.0.0.1:9527
info:
  contact:
    email: wu_yiqiang@outlook.com
    name: sutter
  description: gin-web框架
  termsOfService: https://github.com/18211167516/Go-Gin-Api
  title: go-api 框架
  version: "1.0"
paths:
  /admin/admin_info:
    post:
      consumes:
      - application/json
      description: 管理员信息获取
      operationId: /admin/admin_info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminInfoOutput'
              type: object
      security:
      - Auth: []
      summary: 管理员信息获取
      tags:
      - 用户管理
  /admin/avatar:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: 管理员头像更新
      operationId: /admin/avatar
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 管理员头像更新
      tags:
      - 用户管理
  /admin/changePassword:
    post:
      consumes:
      - application/json
      description: 修改密码
      operationId: /admin/changePassword
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 修改密码
      tags:
      - 用户管理
  /admin/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      operationId: /admin/login
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginOutput'
              type: object
      summary: 用户登录
      tags:
      - 用户管理
  /admin/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      operationId: /admin/register
      parameters:
      - description: body
        in: body
        name: polygon
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册
      tags:
      - 用户管理
  /admin_login/logout:
    get:
      consumes:
      - application/json
      description: 管理员注销
      operationId: /admin_login/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 管理员注销
      tags:
      - 用户管理
  /file/upload:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: 文件上传
      operationId: /file/upload
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - Auth: []
      summary: 文件上传
      tags:
      - 文件管理
  /flet/newsList:
    post:
      consumes:
      - application/json
      description: 查询资讯
      operationId: /flet/newsList
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - Auth: []
      summary: flutter管理
      tags:
      - flutter管理
  /flet/weather:
    post:
      consumes:
      - application/json
      description: 查询天气信息
      operationId: /flet/weather
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - Auth: []
      summary: flutter管理
      tags:
      - flutter管理
securityDefinitions:
  Auth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
